import type { Metadata } from "next";
import Link from "next/link";
import { Mail, MapPin, MessageCircle, Phone } from "lucide-react";
import { PublicPageShell } from "@/components/layout/public-page-shell";
import { getSiteSettings } from "@/lib/services/site-setting-dal";
import { formatWhatsAppUrl } from "@/lib/utils";

export const metadata: Metadata = { title: "تواصل معنا", description: "قنوات التواصل الرسمية مع فريق مسامر لخدمات الضيافة." };
export default async function ContactPage() {
  const settings = await getSiteSettings(); const social = [{ label: "فيسبوك", url: settings.facebookUrl }, { label: "تويتر", url: settings.xUrl }, { label: "إنستغرام", url: settings.instagramUrl }, { label: "سناب شات", url: settings.snapchatUrl }].filter((item): item is { label: string; url: string } => Boolean(item.url));
  return <PublicPageShell><div className={`relative bg-cover bg-center py-16 sm:py-24 ${settings.contactBackgroundPath ? "" : "bg-arabesque-subtle"}`} style={settings.contactBackgroundPath ? { backgroundImage: `url(${JSON.stringify(settings.contactBackgroundPath)})` } : undefined}>{settings.contactBackgroundPath && <div className="absolute inset-0 bg-[#F8F6F3]/90" aria-hidden="true" />}<div className="relative container mx-auto max-w-5xl px-4 text-center"><h1 className="text-4xl sm:text-6xl font-extrabold text-primary-950">تواصل معنا</h1><p className="text-slate-600 mt-4">نسعد بالإجابة عن استفساراتك، وللطلب استخدم نموذج الخدمة المخصص.</p></div></div><section className="container mx-auto max-w-5xl px-4 py-14"><div className="grid sm:grid-cols-2 gap-4"><a href={`tel:${settings.phone.replace(/\s/g, "")}`} className="rounded-2xl bg-white border border-sand-200 p-6 flex gap-4"><Phone className="text-secondary-600" /><div><p className="font-bold">الهاتف</p><p dir="ltr">{settings.phone}</p></div></a><a href={formatWhatsAppUrl(settings.whatsapp || settings.phone)} target="_blank" rel="noopener noreferrer" className="rounded-2xl bg-white border border-sand-200 p-6 flex gap-4"><MessageCircle className="text-secondary-600" /><div><p className="font-bold">واتساب</p><p>محادثة مباشرة</p></div></a>{settings.email && <a href={`mailto:${settings.email}`} className="rounded-2xl bg-white border border-sand-200 p-6 flex gap-4"><Mail className="text-secondary-600" /><div><p className="font-bold">البريد</p><p>{settings.email}</p></div></a>}{settings.address && <div className="rounded-2xl bg-white border border-sand-200 p-6 flex gap-4"><MapPin className="text-secondary-600" /><div><p className="font-bold">العنوان</p><p>{settings.address}</p></div></div>}</div>{social.length > 0 && <div className="flex flex-wrap justify-center gap-3 mt-8">{social.map((item) => <a key={item.label} href={item.url} target="_blank" rel="noopener noreferrer" className="px-4 py-2 rounded-full border border-sand-200 bg-white">{item.label}</a>)}</div>}<div className="text-center mt-10"><Link href="/request" className="inline-flex rounded-xl bg-secondary-600 text-white px-7 py-3 font-bold">اطلب الخدمة</Link></div></section></PublicPageShell>;
}
